version: '3'
services: 
  jenkins:
    container_name: 'jenkins'
    image: jenkins/jenkins:lts
    restart: always
    user: root //设置jenkins对宿主机的权限
    ports: 
    - "10050:8080"
    - "50000:50000"
    - "10051:10051"
    volumes:
    - /srv/docker/jenkins/data:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock